// import "./partials/_hotspots"
// import "./partials/_raycaster"
// import "./partials/_comments"
// import "./partials/_floor"
// // import "./partials/_media"
// import "./partials/_clinics"
import "./partials/_controller"